### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by NicoVermeir** [RodneyWimberly/Windows.Devices.Radios.nRF24L01P#3]
I'm trying to use this library but I get the following error:

> The type Windows.Devices.Radios.nRF24L01P.Logging.DebugOutLoggerFactoryAdapter does not have a constructor that takes the parameters (String).

here's my code:
private void OnLoaded(object sender, RoutedEventArgs routedEventArgs)
{
    GpioController gpioController = GpioController.GetDefault();
    _cePin = gpioController.InitGpioPin(22, GpioPinDriveMode.Output);
    _powerPin = gpioController.InitGpioPin(24, GpioPinDriveMode.Output);
    DeviceInformationCollection devicesInfo = DeviceInformation.FindAllAsync(SpiDevice.GetDeviceSelector("SPI0")).GetAwaiter().GetResult();
    _spiDevice = SpiDevice.FromIdAsync(devicesInfo[0].Id, new SpiConnectionSettings(0)).GetAwaiter().GetResult();
    _commandProcessor = new CommandProcessor(_spiDevice); 
    _radio = new Radio(_commandProcessor, _powerPin, _cePin);
    Debug.WriteLine(_radio.GetArduinoDetails());
}

the error throws on 
_radio = new Radio(_commandProcessor, _powerPin, _cePin);

**Comment by RodneyWimberly** [comment]
Thanks for the report. My apologies you are encountering this issue.  I
will look into this tonight when I get off work..

**Comment by RodneyWimberly** [comment]
I need to dig deeper if this suggestion doesn't work but at first glance I
wonder if you have all of the dependent NuGet packages. It appears I didn't
add them to the NuGet package like I should have. In particular I think you
are missing the Common.Logging.WinRT v3.3.1 NuGet library. Here is a list
of the dependencies. Can you please make sure you add these dependencies to
your project and let me know if this works for you? Assuming that it does
fix you issue I will release a new NuGet package and properly include the
dependencies.

Thanks in advance,

Rodney

"dependencies": {
    "Common.Logging.WinRT": "3.3.1",
    "Microsoft.IoT.DeviceCore": "1.0.3",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Newtonsoft.Json": "8.0.3",
    "Unity": "4.0.1"
  },

**Comment by NicoVermeir** [comment]
yeah I figured out those dependencies, not having those gave me other errors, so I have those in my project now. Let me know if I can try or test anything else, happy to help :)

**Comment by NicoVermeir** [comment]
I got it to work yesterday by downloading the code and removing everything logger related, I basically removed the issue :)
so, it works for me now but the issue still exists in the Nuget package.

My advice: remove the dependencies on the logging framework and unity. most users will already have their own logging / DI solution, so having a dependency on others just makes the application bigger and heavier to run. (just my 2 cents)

**Comment by RodneyWimberly** [comment]
I understand your concerns around the logging and DI. My reason for adding
it was just your point. I want others to be able to register their own
logger if they wanted. I was just laying out the ground work to make that
happen. However based on the issue you had I was debating removing it as
well. I am confused why you were having the issue and I'm not. The
CommonLogging framework comes with it's own DebugOutputAdapter but it
doesn't work so I just wrote my own. It seems the one I wrote isn't working
in your environment.

I am happy to see it is working for you. Would you consider creating a
branch with your changes? If so I might just merge it to the master and
release a new package. I need to think a little about it but the current
state of the DI/Logging isn't benefiting anyone so I might as well remove
it now from the release version and consider what to do in future versions.
I am neck deep in the Arduino side of my current project and hadn't been
able to give this much attention.

Let me know if you have any other problems, question, concerns, or ideas
for improvement.

Rodney

**Comment by NicoVermeir** [comment]
sure, I'll give it a go and do a pull request. might take a few days if that's okay

**Comment by RodneyWimberly** [comment]
Nico,

I just made package 1.2.2 with the following changes. I did remove the IoC
as it was overkill but I keep the Common.Logging.WinRT (I did however
remove several dependencies that weren't truly needed). I just made it
where you pass me the LoggerAdapter via DI to the Radio constructor. This
will allow the usage of any of the included adapters (NoOp, DebugOut, and
SimpleFile) or implement the ILoggerFactoryAdapter and ILog interfaces with
your own logger and pass them in. I think this is the best all around
as Common.Logging.WinRT framework is very lightweight, allow me to do
uniform logging in my library but lets the person consuming my library
choose how they want it to work.

Let me know what you think.

NuGet Package 1.2.2
* Add correct NuGet Dependencies to NuGet Package
* Remove the following dependencies:
    * "Common.Logging.WinRT": "3.3.1",
    * "Microsoft.IoT.DeviceCore": "1.0.3",
    * "Newtonsoft.Json": "8.0.3",
    * "Unity": "4.0.1"
* Moved Logging Components out to new package named Common.Logging.WinRT.Extras
* Added reference to new package named Common.Logging.WinRT.Extras
* Removed IoC Container
* Moved the logging dependency to DI. Now you can pass in the Logging
dependency to the Radio constructor.
  You can use the NoOpLoggerFactoryAdapter to basically disable
logging, use the DebugOutLoggerFactoryAdapter,
SimpleFileLoggerFactoryAdapter, or
  implement ILoggerFactoryAdapter and ILog to use you own logger.


Rodney Wimberly

**Comment by NicoVermeir** [comment]
Looks good to me :)

**Comment by RodneyWimberly** [comment]
Have you had a chance to test the new version? I'd like to get this issue closed if you agree that the new version resolves your issues. If it doesn't resolve your issues I am happy to make other changes to get it resolved for you. If you are having the problem then its highly likely that others are having the problem as well. 

I am just about done with the conversion of RF24Network in .NET using my radio code. I have pulled the Roles out of the Radio package as well and will be releasing them separately as well. I'd like to make sure the Radio package is working well before I release the new packages. So my NuGet packages will be:
1. Common.Logging.WinRT.Extras
2. Windows.Devices.Radios.nRF24L01P - Compatible with the Arduino RF24 libraries
3. Windows.Devices.Radios.nRF24L01P.Simple - Previously the Roles namespace in Windows.Devices.Radios.nRF24L01P
4. Windows.Devices.Radios.nRF24L01P.Network - Compatible with the Arduino RF24Network libraries. This include fragmentation to send messages larger that 32 bytes (max packet size), logical addressing strategy (using a fat tree topology), packet routing (node B can be used to relay a message from node A to node C even if node A and node C are out of range from each other), Unicast and Multicast addressing, and packet acknowledgements

Please let me know what we need to do to get this issue closed.

Thanks in advance,

Rodney Wimberly

**Comment by NicoVermeir** [comment]
sorry, didn't have a chance to test yet. I'll try to set something up this week
